[package]
name = "calculator"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
path-absolutize = "3.0.13"

[profile.release]
strip = true
opt-level = "s"
lto = true
codegen-units = 1
